### ISSUE TITLE
Compatibility with PDS4 version 1.13.0.0

### ISSUE THREAD

**Issue by LandingEllipse** [NASA-PDS/PLAID#2] opened 2020-01-08 15:17 UTC
Hi there,

I've just taken PLAID for a spin at it seems to be a really nifty tool. However, I am wondering whether there are plans to update PLAID to support v1.13 of the information model? If not, could you provide a rough estimate of the work required to complete such work?

All the best,
Ariel Ladegaard

**Comment by stirlingalgermissen** [comment] 2020-01-09 19:26
Hi Ariel,

We plan on supporting this version – I will get you a timeframe when I have it. Glad to hear the tool is working out for you.

Thanks,
Stirling

**Comment by jordanpadams** [comment] 2020-04-30 00:51
@stirlingalgermissen checking in what the status is here?

**Comment by jordanpadams** [comment] 2021-03-31 23:29
duplicate of #15. working to get this deployed in the next few weeks

**Closed by jordanpadams** 2021-03-31 23:29 UTC
